import type { Metadata } from "next";
import Header from "./components/header";
import Footer from "./components/footer";
import { Geist, Geist_Mono } from "next/font/google";
import Provider from "./provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={geistSans.className} suppressHydrationWarning={true}>
      <body>
        <Provider>
          <div className="flex flex-col min-h-screen max-w-[900px] mx-auto text-sm">
            <Header />
            {children}
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
